export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRY: '1h',
  ACCESS_TOKEN_EXPIRY_SECONDS: 3600,
  REFRESH_TOKEN_EXPIRY: '4h',
  REFRESH_TOKEN_EXPIRY_SECONDS: 14400,
  TWO_FACTOR_TOKEN_EXPIRY: '5m',
  TWO_FACTOR_TOKEN_EXPIRY_SECONDS: 300,
  JWT_ALGORITHM: 'RS256' as const,
  JWT_ISSUER: 'auth-server',
} as const;
