export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRY: '15m',
  ACCESS_TOKEN_EXPIRY_SECONDS: 900,
  REFRESH_TOKEN_EXPIRY: '7d',
  REFRESH_TOKEN_EXPIRY_SECONDS: 604800,
  TWO_FACTOR_TOKEN_EXPIRY: '5m',
  TWO_FACTOR_TOKEN_EXPIRY_SECONDS: 300,
  JWT_ALGORITHM: 'RS256' as const,
  JWT_ISSUER: 'auth-server',
} as const;
